[project]
name = "fastapi-clone-0-9-0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.3.0",
    "pydantic >=0.17,<=0.21.0",
    "starlette==0.11.1",
]
